/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.especialidad;

import controlador.GestionarEspecialidad;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.dominio.Especialidad;

/**
 *
 * @author guill
 */
public class EspecialidadVista extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private String tipo_accion;
    private Especialidad especialidad;
    private GestionarEspecialidad gestionar;
    
    /**
     * Creates new form Especialidad
     */
    public EspecialidadVista(DefaultTableModel modelo) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation( JFrame.DO_NOTHING_ON_CLOSE );
        this.setResizable(false);
        
        this.modelo = modelo;
        this.tipo_accion = "R";
        this.especialidad = new Especialidad();
    }

    EspecialidadVista(DefaultTableModel modelo, Especialidad especialidad, String tipo_accion) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation( JFrame.DO_NOTHING_ON_CLOSE );
        this.setResizable(false);
        
        this.modelo = modelo;
        this.tipo_accion = tipo_accion;
        this.especialidad = especialidad;
        
        this.especialidadTxt.setText( this.especialidad.getNombre() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        especialidadTxt = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();
        cerrarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Especialidad");

        jLabel2.setText("Especialidad:");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        cerrarBtn.setText("Cerrar");
        cerrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(especialidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(guardarBtn)
                        .addGap(52, 52, 52)
                        .addComponent(cerrarBtn)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(especialidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(cerrarBtn))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cerrarBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        this.gestionar = new GestionarEspecialidad();
        this.especialidad.setNombre( this.especialidadTxt.getText() );
        
        if (this.tipo_accion.equals("R")) {
            this.gestionar.registrar(this.especialidad);
        } else if (this.tipo_accion.equals("M")) {
            this.gestionar.modificar(this.especialidad);
        }
        
        this.modelo.setRowCount(0);
        ArrayList<Object> especialidades = this.gestionar.listar();
        for (Object especialidad : especialidades) {
            this.modelo.addRow( ((Especialidad)especialidad).getDatos() );
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_guardarBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarBtn;
    private javax.swing.JTextField especialidadTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
